### ISSUE TITLE
Address issue in Siemens Logo Plugin

### ISSUE THREAD

**Issue by demacus** [mknx/smarthome#150]
Address mapping of I/O seems to be broken, at least for Logo 0BA8.

I could fix it by replacing line 381 in __init.py__ as follows:

346            def getAddressInfo(self, value):
---cut---
376            if typ in ['I', 'Q', 'M', 'NI', 'NQ']:  # I1 Q1 M1
377                MaxBits = int(self.tableVM_IO[typ]['bits'])    # Anzahl bits
378                if address > MaxBits:
379                    raise LOGO('Address out of range. {0}1-{0}{1}'.format(typ, MaxBits))
380                q, r = divmod(address - 1, 8)
381                VMaddr = VMaddr + q  # was VMaddr + q * 8
382                bitNr = r
383                return {'VMaddr': VMaddr, 'VMbit': bitNr, 'typ': typ, 'DataType': 'bit'}
---cut---

Best regards

**Comment by ivan73** [comment]
fixed
