### ISSUE TITLE
komplettanleitung bis zur einbindung eibd via usb klappt, dann nichts mehr...

### ISSUE THREAD

**Issue by hellobello** [mknx/smarthome#199]
Hallo, ich bin gerade dabei die Anleitung zu befolgen, da das smartVISU Image auf meinem Pi2 nicht geht. Allerdings klappt das nur bis zum starten von eibd:

[code]

root@raspberrypi:/etc/init.d# ./eibd start
Segmentation fault
[....] Starting eibd (via systemctl): eibd.serviceJob for eibd.service failed. See 'systemctl status eibd.service' and 'journalctl -xn' for details.
 failed!
root@raspberrypi:/etc/init.d# systemctl status eibd.service
● eibd.service - EIB Daemon
   Loaded: loaded (/lib/systemd/system/eibd.service; enabled)
   Active: failed (Result: timeout) since So 2016-01-31 03:28:00 CET; 34s ago
  Process: 2553 ExecStartPre=/usr/local/bin/eibd-findusb.sh (code=killed, signal=TERM)

Jan 31 03:28:00 raspberrypi systemd[1]: eibd.service start-pre operation timed out. Terminating.
Jan 31 03:28:00 raspberrypi systemd[1]: Failed to start EIB Daemon.
Jan 31 03:28:00 raspberrypi systemd[1]: Unit eibd.service entered failed state.
root@raspberrypi:/etc/init.d# journalctl -xn
-- Logs begin at So 2016-01-31 03:15:13 CET, end at So 2016-01-31 03:28:41 CET. --
Jan 31 03:25:33 raspberrypi ntpd[508]: adjusting local clock by 294120.257910s
Jan 31 03:25:33 raspberrypi ntpd[508]: adjtime failed: Invalid argument
Jan 31 03:25:52 raspberrypi dhcpcd[423]: wlan0: Router Advertisement from fe80::1
Jan 31 03:26:30 raspberrypi systemd[1]: Starting EIB Daemon...
-- Subject: Unit eibd.service has begun with start-up
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit eibd.service has begun starting up.
Jan 31 03:26:49 raspberrypi dhcpcd[423]: wlan0: Router Advertisement from fe80::1
Jan 31 03:27:46 raspberrypi dhcpcd[423]: wlan0: Router Advertisement from fe80::1
Jan 31 03:28:00 raspberrypi systemd[1]: eibd.service start-pre operation timed out. Terminating.
Jan 31 03:28:00 raspberrypi systemd[1]: Failed to start EIB Daemon.
-- Subject: Unit eibd.service has failed
-- Defined-By: systemd
## -- Unit eibd.service has failed.

-- The result is failed.
Jan 31 03:28:00 raspberrypi systemd[1]: Unit eibd.service entered failed state.
Jan 31 03:28:41 raspberrypi dhcpcd[423]: wlan0: Router Advertisement from fe80::1
root@raspberrypi:/etc/init.d# 
[/code]

Sobald ich die IP statisch mache, kommt mein Pi nicht mehr ins internet, deshalb fällt die Möglichkeit weg. Mir iat auch nicht ganz klar was die Netz-IP mit dem USB Port zu tun hat???

Grüße, Michael

**Comment by mknx** [comment]
Hallo Michael,

ich sehe den Zusammenhang zu SH.py nicht. Du hast ein Problem mit dem eibd. Ok, damit kenne ich nicht aus. (Ich habe auch nicht die Anleitung geschrieben). Versuche doch einmal unter http://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/diy-do-it-yourself Hilfe zu bekommen.

Bis bald

Marcus
